baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #13878'

disableKinds = ['page','rss','section','sitemap','taxonomy','term']

theme = ["hugo-13878"]

#[caches.getresource]
#maxAge = 0
